name: Build

on:
  push:
    branches-ignore: [dev]
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python environment
        uses: ./.github/actions/setup-liberation-python

      - name: Set up JS environment
        uses: ./.github/actions/setup-liberation-js

      - name: Set build number
        shell: bash
        run: |
          echo $(git rev-list --count HEAD) > resources/buildnumber
          echo ${GITHUB_SHA:0:7} > resources/gitsha

      - name: Build app
        uses: ./.github/actions/build-app

      - name: Create archive
        run: Compress-Archive -Path .\dist\dcs-retribution\ -DestinationPath dist\dcs-retribution.zip

      - uses: actions/upload-artifact@v4
        with:
          name: dcs-retribution
          path: dist/dcs-retribution.zip
