name: Release

on:
  push:
    tags: ["[0-9]*"]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to release (e.g. 1.6.0)'
        required: true
        type: string

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: [lint, test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
          submodules: true

      - name: Set up Python environment
        uses: ./.github/actions/setup-liberation-python

      - name: Set up JS environment
        uses: ./.github/actions/setup-liberation-js

      - name: Determine version
        id: version
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $version = "${{ inputs.tag }}"
          } else {
            $version = ($env:GITHUB_REF -split "/") | Select-Object -Last 1
          }
          Write-Output "number=$version" >> $env:GITHUB_OUTPUT

      - name: Finalize build
        run: |
          New-Item -ItemType file resources\final
          [IO.File]::WriteAllLines($pwd.path + "\resources\buildnumber", $env:GITHUB_RUN_NUMBER)
          [IO.File]::WriteAllLines($pwd.path + "\resources\gitsha", $env:GITHUB_SHA)

      - name: Build app
        uses: ./.github/actions/build-app
        with:
          release: true

      - name: Create archive and release notes
        shell: pwsh
        run: |
          $version = "${{ steps.version.outputs.number }}"
          Compress-Archive -Path .\dist\dcs-retribution\ -DestinationPath "dist\dcs-retribution.${version}.zip" -CompressionLevel Optimal

          $changelog = Get-Content .\changelog.md
          $last_change = ($changelog | Select-String -Pattern "^#\s" | Select-Object -Skip 1 -First 1).LineNumber - 2
          ($changelog | Select-Object -First $last_change) -join "`n" | Out-File .\releasenotes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.number }}
          name: "Retribution v${{ steps.version.outputs.number }}"
          body_path: dist/releasenotes.md
          draft: false
          prerelease: false
          files: dist/dcs-retribution.${{ steps.version.outputs.number }}.zip

      - name: Send status to Discord
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.discord_webhook_releases }}
          title: "🎉 Retribution v${{ steps.version.outputs.number }} Released!"
          message: "**Download:** https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.number }}"
          include_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub Build Notifier
        if: github.repository == 'Druss99/dcs-retribution'
